// Strait design tokens v5.0.0 — GENERATED by brand/tokens/build.mjs from tokens/src (DTCG 2025.10). Do not edit.
// Spec: design-work/final/DS-V5.md
import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif

public struct StraitColor: Equatable, Sendable {
    public let rgb: UInt32
    public let alpha: Double
    public var red: Double { Double((rgb >> 16) & 0xFF) / 255 }
    public var green: Double { Double((rgb >> 8) & 0xFF) / 255 }
    public var blue: Double { Double(rgb & 0xFF) / 255 }
    public init(_ rgb: UInt32, alpha: Double = 1) { self.rgb = rgb; self.alpha = alpha }
}

#if canImport(SwiftUI)
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension StraitColor {
    var color: Color { Color(.sRGB, red: red, green: green, blue: blue, opacity: alpha) }
}
#endif

public struct StraitColors: Sendable {
    public let bg: StraitColor
    public let bgSubtle: StraitColor
    public let bgMuted: StraitColor
    public let surface: StraitColor
    public let surfaceRaised: StraitColor
    public let surfaceSunken: StraitColor
    public let border: StraitColor
    public let borderStrong: StraitColor
    public let borderControl: StraitColor
    public let text: StraitColor
    public let textMuted: StraitColor
    public let textSubtle: StraitColor
    public let textInverse: StraitColor
    public let brand: StraitColor
    public let brandHover: StraitColor
    public let brandPress: StraitColor
    public let onBrand: StraitColor
    public let brandSubtle: StraitColor
    public let brandBorder: StraitColor
    public let brandText: StraitColor
    public let link: StraitColor
    public let linkHover: StraitColor
    public let focusRing: StraitColor
    public let field: StraitColor
    public let onField: StraitColor
    public let night: StraitColor
    public let onNight: StraitColor
    public let onNightMuted: StraitColor
    public let lane: StraitColor
    public let laneText: StraitColor
    public let accent: StraitColor
    public let accentText: StraitColor
    public let success: StraitColor
    public let successBg: StraitColor
    public let warning: StraitColor
    public let warningBg: StraitColor
    public let danger: StraitColor
    public let dangerBg: StraitColor
    public let info: StraitColor
    public let infoBg: StraitColor
    public let chart1: StraitColor
    public let chart2: StraitColor
    public let chart3: StraitColor
    public let chart4: StraitColor
    public let chart5: StraitColor
    public let chart6: StraitColor
    public let scrim: StraitColor
    public let logoMark: StraitColor
    public let logoWord: StraitColor
    public let statusOk: StraitColor
    public let statusOkBg: StraitColor
    public let statusDegraded: StraitColor
    public let statusDegradedBg: StraitColor
    public let statusBroken: StraitColor
    public let statusBrokenBg: StraitColor
    public let statusUnknown: StraitColor
    public let statusUnknownBg: StraitColor
    public let certaintyExact: StraitColor
    public let certaintyExactBg: StraitColor
    public let certaintyLikely: StraitColor
    public let certaintyLikelyBg: StraitColor
    public let certaintyEstimated: StraitColor
    public let certaintyEstimatedBg: StraitColor
    public let certaintyFailed: StraitColor
    public let certaintyFailedBg: StraitColor
    public let chartOther: StraitColor
    public let chartGrid: StraitColor
    public let chartAxis: StraitColor
    public let chartFocus: StraitColor
    public let seq1: StraitColor
    public let seq2: StraitColor
    public let seq3: StraitColor
    public let seq4: StraitColor
    public let seq5: StraitColor
    public let divergingNeg: StraitColor
    public let divergingMid: StraitColor
    public let divergingPos: StraitColor
    public let paper: StraitColor
    public let paperInk: StraitColor
    public let paperMuted: StraitColor
    public let paperSubtle: StraitColor
    public let paperLine: StraitColor
    public let paperHl: StraitColor
    public let paperStamp: StraitColor
}

public struct StraitTextStyle: Sendable {
    public let family: String
    public let size: Double
    public let lineHeight: Double
    public let weight: Int
    public let letterSpacingEm: Double
}

public enum StraitTokens {
    public static let version = "5.0.0"

    public static let light = StraitColors(
        bg: StraitColor(0xFFFFFF),
        bgSubtle: StraitColor(0xF7F5F1),
        bgMuted: StraitColor(0xEFECE6),
        surface: StraitColor(0xFFFFFF),
        surfaceRaised: StraitColor(0xFFFFFF),
        surfaceSunken: StraitColor(0xF7F5F1),
        border: StraitColor(0xE8E4DD),
        borderStrong: StraitColor(0xD2CBC1),
        borderControl: StraitColor(0x7A7166),
        text: StraitColor(0x0F0D0A),
        textMuted: StraitColor(0x423B33),
        textSubtle: StraitColor(0x5F574D),
        textInverse: StraitColor(0xFFFFFF),
        brand: StraitColor(0xFF6A13),
        brandHover: StraitColor(0xFF8237),
        brandPress: StraitColor(0xE85600),
        onBrand: StraitColor(0x0F0D0A),
        brandSubtle: StraitColor(0xFFF4EC),
        brandBorder: StraitColor(0xFFC49E),
        brandText: StraitColor(0xB84200),
        link: StraitColor(0xB84200),
        linkHover: StraitColor(0x8A3304),
        focusRing: StraitColor(0xE85600),
        field: StraitColor(0xFF6A13),
        onField: StraitColor(0x0F0D0A),
        night: StraitColor(0x0E0C0A),
        onNight: StraitColor(0xF6F3EE),
        onNightMuted: StraitColor(0xB8B0A5),
        lane: StraitColor(0xE85600),
        laneText: StraitColor(0xB84200),
        accent: StraitColor(0xE85600),
        accentText: StraitColor(0xB84200),
        success: StraitColor(0x33701B),
        successBg: StraitColor(0xEEF4E4),
        warning: StraitColor(0x8A5A00),
        warningBg: StraitColor(0xFBF1DC),
        danger: StraitColor(0xB3261E),
        dangerBg: StraitColor(0xFBEAE6),
        info: StraitColor(0x5F574D),
        infoBg: StraitColor(0xF7F5F1),
        chart1: StraitColor(0xE85600),
        chart2: StraitColor(0xB84200),
        chart3: StraitColor(0x8A3304),
        chart4: StraitColor(0x5F574D),
        chart5: StraitColor(0x7A7166),
        chart6: StraitColor(0x423B33),
        scrim: StraitColor(0x0F0D0A, alpha: 0.48),
        logoMark: StraitColor(0xFF6A13),
        logoWord: StraitColor(0x0F0D0A),
        statusOk: StraitColor(0x33701B),
        statusOkBg: StraitColor(0xEEF4E4),
        statusDegraded: StraitColor(0x8A5A00),
        statusDegradedBg: StraitColor(0xFBF1DC),
        statusBroken: StraitColor(0xB3261E),
        statusBrokenBg: StraitColor(0xFBEAE6),
        statusUnknown: StraitColor(0x5F574D),
        statusUnknownBg: StraitColor(0xEFECE6),
        certaintyExact: StraitColor(0xB84200),
        certaintyExactBg: StraitColor(0xFFF4EC),
        certaintyLikely: StraitColor(0xB84200),
        certaintyLikelyBg: StraitColor(0xFFF4EC),
        certaintyEstimated: StraitColor(0x7A7166),
        certaintyEstimatedBg: StraitColor(0xEFECE6),
        certaintyFailed: StraitColor(0xB3261E),
        certaintyFailedBg: StraitColor(0xFBEAE6),
        chartOther: StraitColor(0x7A7166),
        chartGrid: StraitColor(0xE8E4DD),
        chartAxis: StraitColor(0xD2CBC1),
        chartFocus: StraitColor(0x0F0D0A),
        seq1: StraitColor(0xFFF4EC),
        seq2: StraitColor(0xFFC49E),
        seq3: StraitColor(0xFF8237),
        seq4: StraitColor(0xE85600),
        seq5: StraitColor(0x8A3304),
        divergingNeg: StraitColor(0x7A7166),
        divergingMid: StraitColor(0xEFECE6),
        divergingPos: StraitColor(0xFF6A13),
        paper: StraitColor(0xF7F2E8),
        paperInk: StraitColor(0x1A1612),
        paperMuted: StraitColor(0x4A4238),
        paperSubtle: StraitColor(0x62594D),
        paperLine: StraitColor(0xCFC5B6),
        paperHl: StraitColor(0xEAE2D4),
        paperStamp: StraitColor(0xB84200)
    )

    public static let dark = StraitColors(
        bg: StraitColor(0x0E0C0A),
        bgSubtle: StraitColor(0x14120F),
        bgMuted: StraitColor(0x221E1A),
        surface: StraitColor(0x191613),
        surfaceRaised: StraitColor(0x221E1A),
        surfaceSunken: StraitColor(0x0A0908),
        border: StraitColor(0x2B2621),
        borderStrong: StraitColor(0x3E3831),
        borderControl: StraitColor(0x7D746A),
        text: StraitColor(0xF6F3EE),
        textMuted: StraitColor(0xB8B0A5),
        textSubtle: StraitColor(0x9A9186),
        textInverse: StraitColor(0x0F0D0A),
        brand: StraitColor(0xFF6A13),
        brandHover: StraitColor(0xFF8237),
        brandPress: StraitColor(0xE85600),
        onBrand: StraitColor(0x0F0D0A),
        brandSubtle: StraitColor(0x2A1A10),
        brandBorder: StraitColor(0x5C2306),
        brandText: StraitColor(0xFF8237),
        link: StraitColor(0xFF8237),
        linkHover: StraitColor(0xFF9C5E),
        focusRing: StraitColor(0xFF8237),
        field: StraitColor(0xFF6A13),
        onField: StraitColor(0x0F0D0A),
        night: StraitColor(0x0E0C0A),
        onNight: StraitColor(0xF6F3EE),
        onNightMuted: StraitColor(0xB8B0A5),
        lane: StraitColor(0xFF8237),
        laneText: StraitColor(0xFF8237),
        accent: StraitColor(0xFF8237),
        accentText: StraitColor(0xFF8237),
        success: StraitColor(0x84C46A),
        successBg: StraitColor(0x16200F),
        warning: StraitColor(0xE8B04A),
        warningBg: StraitColor(0x2A2010),
        danger: StraitColor(0xF0645C),
        dangerBg: StraitColor(0x2B1513),
        info: StraitColor(0xB8B0A5),
        infoBg: StraitColor(0x191613),
        chart1: StraitColor(0xFF6A13),
        chart2: StraitColor(0xFF9C5E),
        chart3: StraitColor(0xFFC49E),
        chart4: StraitColor(0xB84200),
        chart5: StraitColor(0x9A9186),
        chart6: StraitColor(0xB8B0A5),
        scrim: StraitColor(0x000000, alpha: 0.64),
        logoMark: StraitColor(0xFF6A13),
        logoWord: StraitColor(0xF6F3EE),
        statusOk: StraitColor(0x84C46A),
        statusOkBg: StraitColor(0x16200F),
        statusDegraded: StraitColor(0xE8B04A),
        statusDegradedBg: StraitColor(0x2A2010),
        statusBroken: StraitColor(0xF0645C),
        statusBrokenBg: StraitColor(0x2B1513),
        statusUnknown: StraitColor(0xB8B0A5),
        statusUnknownBg: StraitColor(0x221E1A),
        certaintyExact: StraitColor(0xFF8237),
        certaintyExactBg: StraitColor(0x2A1A10),
        certaintyLikely: StraitColor(0xFF9C5E),
        certaintyLikelyBg: StraitColor(0x2A1A10),
        certaintyEstimated: StraitColor(0x9A9186),
        certaintyEstimatedBg: StraitColor(0x221E1A),
        certaintyFailed: StraitColor(0xF0645C),
        certaintyFailedBg: StraitColor(0x2B1513),
        chartOther: StraitColor(0x9A9186),
        chartGrid: StraitColor(0x2B2621),
        chartAxis: StraitColor(0x3E3831),
        chartFocus: StraitColor(0xF6F3EE),
        seq1: StraitColor(0x2A1A10),
        seq2: StraitColor(0x5C2306),
        seq3: StraitColor(0xB84200),
        seq4: StraitColor(0xFF6A13),
        seq5: StraitColor(0xFFC49E),
        divergingNeg: StraitColor(0x9A9186),
        divergingMid: StraitColor(0x2B2621),
        divergingPos: StraitColor(0xFF6A13),
        paper: StraitColor(0xEBE3D3),
        paperInk: StraitColor(0x1A1612),
        paperMuted: StraitColor(0x4A4238),
        paperSubtle: StraitColor(0x62594D),
        paperLine: StraitColor(0xCFC5B6),
        paperHl: StraitColor(0xE0D6C3),
        paperStamp: StraitColor(0xA33A00)
    )

    public static func colors(dark: Bool) -> StraitColors { dark ? self.dark : self.light }

    public enum Space {
        public static let s0: Double = 0.0
        public static let s1: Double = 4.0
        public static let s2: Double = 8.0
        public static let s3: Double = 12.0
        public static let s4: Double = 16.0
        public static let s5: Double = 20.0
        public static let s6: Double = 24.0
        public static let s8: Double = 32.0
        public static let s10: Double = 40.0
        public static let s12: Double = 48.0
        public static let s16: Double = 64.0
        public static let s20: Double = 80.0
        public static let s24: Double = 96.0
        public static let s32: Double = 128.0
        public static let s40: Double = 160.0
        public static let s05: Double = 2.0
    }

    public enum Radius {
        public static let xs: Double = 4.0
        public static let sm: Double = 6.0
        public static let md: Double = 8.0
        public static let lg: Double = 12.0
        public static let xl: Double = 16.0
        public static let r2xl: Double = 20.0
        public static let full: Double = 999.0
    }

    public enum Font {
        public static let display = "Bricolage Grotesque"
        public static let body = "Inter"
        public static let mono = "JetBrains Mono"
    }

    public enum Text {
        public static let displayPoster = StraitTextStyle(family: "display", size: 192.0, lineHeight: 166.0, weight: 700, letterSpacingEm: -0.05)
        public static let displayHero = StraitTextStyle(family: "display", size: 74.0, lineHeight: 70.0, weight: 700, letterSpacingEm: -0.035)
        public static let displayXl = StraitTextStyle(family: "display", size: 64.0, lineHeight: 64.0, weight: 700, letterSpacingEm: -0.035)
        public static let displayLg = StraitTextStyle(family: "display", size: 56.0, lineHeight: 57.0, weight: 700, letterSpacingEm: -0.03)
        public static let h1 = StraitTextStyle(family: "display", size: 32.0, lineHeight: 38.0, weight: 700, letterSpacingEm: -0.02)
        public static let pageTitle = StraitTextStyle(family: "display", size: 24.0, lineHeight: 30.0, weight: 700, letterSpacingEm: -0.015)
        public static let h2 = StraitTextStyle(family: "display", size: 24.0, lineHeight: 30.0, weight: 700, letterSpacingEm: -0.015)
        public static let h3 = StraitTextStyle(family: "display", size: 19.0, lineHeight: 26.0, weight: 700, letterSpacingEm: -0.01)
        public static let h4 = StraitTextStyle(family: "body", size: 15.0, lineHeight: 22.0, weight: 600, letterSpacingEm: 0.0)
        public static let sectionTitle = StraitTextStyle(family: "body", size: 16.0, lineHeight: 22.0, weight: 600, letterSpacingEm: 0.0)
        public static let verdict = StraitTextStyle(family: "body", size: 16.0, lineHeight: 24.0, weight: 500, letterSpacingEm: 0.0)
        public static let lead = StraitTextStyle(family: "body", size: 20.0, lineHeight: 30.0, weight: 400, letterSpacingEm: 0.0)
        public static let bodyLg = StraitTextStyle(family: "body", size: 17.0, lineHeight: 28.0, weight: 400, letterSpacingEm: 0.0)
        public static let bodyMd = StraitTextStyle(family: "body", size: 15.0, lineHeight: 24.0, weight: 400, letterSpacingEm: 0.0)
        public static let body = StraitTextStyle(family: "body", size: 14.0, lineHeight: 21.0, weight: 400, letterSpacingEm: 0.0)
        public static let cardTitle = StraitTextStyle(family: "body", size: 14.0, lineHeight: 20.0, weight: 600, letterSpacingEm: 0.0)
        public static let bodySm = StraitTextStyle(family: "body", size: 13.0, lineHeight: 19.0, weight: 400, letterSpacingEm: 0.0)
        public static let caption = StraitTextStyle(family: "body", size: 12.0, lineHeight: 16.0, weight: 500, letterSpacingEm: 0.01)
        public static let overline = StraitTextStyle(family: "mono", size: 12.0, lineHeight: 16.0, weight: 500, letterSpacingEm: 0.08)
        public static let station = StraitTextStyle(family: "mono", size: 12.0, lineHeight: 16.0, weight: 500, letterSpacingEm: 0.06)
        public static let label = StraitTextStyle(family: "mono", size: 12.0, lineHeight: 17.0, weight: 500, letterSpacingEm: 0.08)
        public static let codeLg = StraitTextStyle(family: "mono", size: 14.0, lineHeight: 22.0, weight: 400, letterSpacingEm: 0.0)
        public static let code = StraitTextStyle(family: "mono", size: 13.0, lineHeight: 20.0, weight: 400, letterSpacingEm: 0.0)
        public static let codeSm = StraitTextStyle(family: "mono", size: 12.0, lineHeight: 16.0, weight: 400, letterSpacingEm: 0.0)
        public static let receipt = StraitTextStyle(family: "mono", size: 13.0, lineHeight: 21.0, weight: 400, letterSpacingEm: 0.0)
        public static let receiptHead = StraitTextStyle(family: "mono", size: 13.0, lineHeight: 17.0, weight: 600, letterSpacingEm: 0.06)
        public static let kbd = StraitTextStyle(family: "mono", size: 12.0, lineHeight: 16.0, weight: 500, letterSpacingEm: 0.0)
        public static let metricXl = StraitTextStyle(family: "mono", size: 64.0, lineHeight: 64.0, weight: 600, letterSpacingEm: -0.02)
        public static let metric = StraitTextStyle(family: "display", size: 28.0, lineHeight: 32.0, weight: 700, letterSpacingEm: -0.02)
        public static let metricSm = StraitTextStyle(family: "body", size: 20.0, lineHeight: 24.0, weight: 600, letterSpacingEm: 0.0)
        public static let receiptTotal = StraitTextStyle(family: "display", size: 36.0, lineHeight: 36.0, weight: 700, letterSpacingEm: -0.02)
        public static let stamp = StraitTextStyle(family: "display", size: 14.0, lineHeight: 14.0, weight: 700, letterSpacingEm: 0.1)
    }

    /// Seconds. Use 0 when UIAccessibility.isReduceMotionEnabled.
    public enum Duration {
        public static let instant: TimeInterval = 0
        public static let fast: TimeInterval = 0.12
        public static let stagger: TimeInterval = 0.12
        public static let draw: TimeInterval = 0.16
        public static let base: TimeInterval = 0.2
        public static let step: TimeInterval = 0.24
        public static let slow: TimeInterval = 0.28
        public static let wipe: TimeInterval = 0.32
        public static let reveal: TimeInterval = 0.4
        public static let ink: TimeInterval = 0.42
        public static let mark: TimeInterval = 0.48
        public static let cut: TimeInterval = 0.52
        public static let print: TimeInterval = 0.64
        public static let route: TimeInterval = 0.9
        public static let scene: TimeInterval = 1.2
        public static let travel: TimeInterval = 1.6
        public static let pulse: TimeInterval = 2.4
        public static let delayResume: TimeInterval = 4
    }

    /// Cubic-bezier control points (x1, y1, x2, y2): SwiftUI `.timingCurve(a, b, c, d, duration:)`.
    public enum Easing {
        public static let standard: [Double] = [0.2, 0.0, 0.0, 1.0]
        public static let enter: [Double] = [0.2, 0.8, 0.2, 1.0]
        public static let exit: [Double] = [0.4, 0.0, 1.0, 1.0]
        public static let route: [Double] = [0.65, 0.0, 0.35, 1.0]
        public static let emphasized: [Double] = [0.3, 0.0, 0.0, 1.2]
    }

    public enum Layout {
        public static let bpSm: Double = 480.0
        public static let bpMd: Double = 768.0
        public static let bpLg: Double = 1024.0
        public static let bpXl: Double = 1280.0
        public static let phoneMin: Double = 360.0
        public static let contentMax: Double = 1120.0
        public static let contentWide: Double = 1200.0
        public static let gutter: Double = 16.0
        public static let gutterMd: Double = 24.0
        public static let sectionY: Double = 160.0
        public static let sectionYMd: Double = 96.0
        public static let sectionYSm: Double = 64.0
        public static let heroTop: Double = 120.0
        public static let appSidebar: Double = 232.0
        public static let appHeaderH: Double = 56.0
        public static let controlSm: Double = 32.0
        public static let controlMd: Double = 36.0
        public static let controlLg: Double = 44.0
        public static let rowComfortable: Double = 48.0
        public static let rowCompact: Double = 32.0
        public static let touchMin: Double = 44.0
        public static let headerH: Double = 64.0
    }

    public enum Component {
        public static let seamDot: Double = 8.0
        public static let seamHalo: Double = 4.0
        public static let railNode: Double = 32.0
        public static let railLine: Double = 2.0
        public static let ticketCorner: Double = 12.0
        public static let ticketNotch: Double = 12.0
        public static let ticketPerf: Double = 2.5
        public static let ticketPerfGap: Double = 12.0
        public static let halfMarkW: Double = 21.0
        public static let halfMarkH: Double = 24.0
        public static let chipH: Double = 22.0
        public static let glyphStatus: Double = 18.0
        public static let glyph: Double = 24.0
        public static let strokeGlyph: Double = 1.5
        public static let strokeStatus: Double = 2.0
        public static let stampRotate: Double = -6.0
        public static let anatomyBorder: Double = 2.0
        public static let cardPad: Double = 28.0
    }
}
